### ISSUE TITLE
Mojave compatibility issues

### ISSUE THREAD

**Issue by KernelPanicAUS** [tonytonyjan/jaro_winkler#22]
This gem seems to have some compatibility issues with Mac os x Mojave.

```
$ sudo gem install rubocop

current directory: /Library/Ruby/Gems/2.3.0/gems/jaro_winkler-1.5.1/ext/jaro_winkler
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181104-27213-qfkou.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.3.0/gems/jaro_winkler-1.5.1/ext/jaro_winkler
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.3.0/gems/jaro_winkler-1.5.1/ext/jaro_winkler
make "DESTDIR="
make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by `adj_matrix.o'.  Stop.

make failed, exit code 2
```

Any ideas how this can be fixed?

**Comment by KernelPanicAUS** [comment]
that seems to have blown up as well

```
"xcrun clang -o conftest -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18 -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/backward -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS  conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib -L.     -lruby.2.3.0  -lpthread -ldl -lobjc  "
In file included from conftest.c:1:
In file included from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h:33:
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^~~~~~~~~~~~~~~
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

```

I'm using a new Mac and have only justed upgraded to Mojave, so its a very clean environment and have not installed these gems at all prior to the upgrade.

I have double checked and I definitely have the xcode command line tools installed...

**Comment by rodrigobdz** [comment]
I'm also having this issue. I have Xcode Command Line Tools installed. Related to https://github.com/rubocop-hq/rubocop/issues/5989.

It happens when I try to install either `rubocop` or `jaro_winkler`.
<details>
  <summary>rubocop installation error</summary>

  ![image](https://user-images.githubusercontent.com/14152377/48070883-2df53e80-e1d9-11e8-863c-c1f893ddc655.png)

</details>
<details>
  <summary>jaro_winkler installation error</summary>

![image](https://user-images.githubusercontent.com/14152377/48070827-1322ca00-e1d9-11e8-8671-dd4e6ee7194f.png)

</details>

**Comment by tiiiecherle** [comment]
It seems like a lot of people having the issue.

[https://github.com/Homebrew/homebrew-cask/issues/52775](https://github.com/Homebrew/homebrew-cask/issues/52775)

Would be nice to see a fix in the near future. Thanks

**Comment by tonytonyjan** [comment]
@rodrigobdz The images you gave does not contain informations, you have to provde the contents of`gem_make.out` file, check the last line in your images, thanks.

**Comment by rodrigobdz** [comment]
`gem_make.out` does not contain any additional information.
![image](https://user-images.githubusercontent.com/14152377/48432295-408cec00-e774-11e8-906c-7e4d0208ae60.png)

**Comment by KernelPanicAUS** [comment]
I've managed to overcome this issue with the following steps:

- Use `chruby` and `ruby-install` to install a clean version of ruby.
- Install the full xcode package and its cli tools.

Since then I've managed to install a whole bunch of gems with native extensions without any issues.

This leads me to suspect that the version of ruby shipped with Mojave is missing a bunch of C headers that make installing any gems with native extensions a massive pain in the rear.

It might be worth adding something to the Readme for Mojave users 🤔

**Comment by EricFromCanada** [comment]
The problem is that Apple can't decide whether to keep that `include` directory around…

- 10.11: `/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include` exists.
- 10.12: `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include` does not exist.
- 10.13: ^ that directory ^ **does** exist.
- 10.14: ^ that directory ^ **does not** exist.

Strange.
